<?php
use Drupal\Core\Routing\RouteMatchInterface;

/**
* Implements hook_help().
*/
function scales_app_help($route_name, RouteMatchInterface $route_match) {

switch ($route_name) {
case 'help.page.scales_app':
$output = '';
$output .= '<h3>' . t('About') . '</h3>';
$output .= '<p>' . t('This is a custom module that uses route parameters to generate scales exercises.') .
  '</p>';
return $output;

default:
}
}
