<?php

/**
 * @file
 * Amdj Message module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function amdj_message_help($route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {
    case 'help.page.amdj_message':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a custom module that outputs a message.') . '</p>';
      return $output;

    default:
  }
}
