name: test
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  testing:
    name: Drupal ${{ matrix.drupal-core }} - PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        drupal-core: ['9.3.x', '9.4.x']
        php-versions: ['7.4', 8.0']
    steps:
      - name: Checkout Drupal core
        uses: actions/checkout@v2
        with:
          repository: drupal/drupal
          ref: ${{ matrix.drupal-core }}

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Drupal core dependencies
        run: composer --no-interaction --no-progress --prefer-dist --optimize-autoloader install

      - name: Install Coder module
        run: composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true &&
             composer --dev --no-interaction --no-progress require drupal/coder:8.3.15

      - name: Check coding standards
        run: ./vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
             ./vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,install,js modules/custom/amdj_message

      - name: Setup PHPUnit tests
        uses: php-actions/phpunit@v9
        with:
          #version: 9.5.21 # you must specify the major version used in composer.json
          configuration: tests/phpunit/phpunit.xml # This is the default

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit web/modules/custom/amdj_message/tests/src/Functional/SkeletonTest.php
